title: Bennington Area Robotics
description: Community-based youth robotics teams supporting STEM education in the greater Bennington Vermont area.
url: https://robotics.bamvt.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from
