title: Bennington Area Robotics
description: Community-based youth robotics teams supporting STEM education in the greater Bennington area.
url: https://bennington-area-robotics.github.io

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from
